---
- name: Add SonarQube token to Jenkins
  hosts: servers
  vars:
    jenkins_host: "34.213.245.87"   # Jenkins server IP or hostname
    jenkins_user: "rithi"            # Jenkins user
    jenkins_password: "1143ccec920b9ce2939dfa3ebe86c5e35f"  # Jenkins API token (not password)
    sonar_token: " sqp_51ddbf3421dd6644f063604a35942cf553d370ca"  # SonarQube token

  tasks:
    - name: Get Jenkins Crumb
      uri:
        url: "http://{{ jenkins_host }}:8080/crumbIssuer/api/json"
        method: GET
        user: "{{ jenkins_user }}"
        password: "{{ jenkins_password }}"
        force_basic_auth: yes
        return_content: yes
      register: jenkins_crumb

    - name: Add SonarQube token to Jenkins credentials store
      uri:
        url: "http://{{ jenkins_host }}:8080/manage/credentials/store/system/domain/_/createCredentials"
        method: POST
        user: "{{ jenkins_user }}"
        password: "{{ jenkins_password }}"
        force_basic_auth: yes
        follow_redirects: all  # This allows following redirects
        headers:
          Content-Type: "application/x-www-form-urlencoded"
          Jenkins-Crumb: "{{ jenkins_crumb.json.crumb }}"
        body: "json={{ {'': '0', 'credentials': { 'scope': 'GLOBAL', 'id': 'sonarqube-token', 'secret': sonar_token, 'description': 'SonarQube Token', '$class': 'org.jenkinsci.plugins.plaincredentials.impl.StringCredentialsImpl' }} | to_json | urlencode }}"
        status_code: 200